backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "paginas"
    label: "Páginas do Site"
    files:
      - file: "index.html"
        label: "Página Inicial"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }
          - { label: "Imagem", name: "image", widget: "image" }
